name: Build and Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean install

    - name: Prepare application.properties
      run: |
        mkdir config
        echo "${{ secrets.APP_PROPERTIES }}" > config/application.properties

    - name: web docker build and push
      run: |
          docker login -u ${{ secrets.DOCKER_KEY }}
          docker build -t ${{ secrets.DOCKER_REPO }}/challengers-backend:latest .
          docker push ${{ secrets.DOCKER_REPO }}/challengers-backend

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop challengers-backend
          docker rm challengers-backend
          docker pull ${{ secrets.DOCKER_REPO }}/challengers-backend:latest
          docker run -d -p 8080:8080 --name challengers-backend ${{ secrets.DOCKER_REPO }}/challengers-backend:latest
